services:
  local:
    build:
      dockerfile: "Dockerfile"
      target: "local"
    environment:
      GOCACHE: /cache/go-build
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ./tmp/cache
        target: /cache/go-build
    env_file: ".env"
    
  lint:
    image: golangci/golangci-lint:v1
    command: "golangci-lint run -v"
    working_dir: "/app"
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: true

  deploy:
    build:
      dockerfile: "Dockerfile"
      target: "deploy"
    env_file: ".env"
